baseURL = "https://blog.hallotron.fyi/"
languageCode = "en-US"
title = "Hallotron journey"
theme = "gokarna-hugo"
buildFuture = true
paginate = 10
mainSections = ["posts", "pictures"]

[params]
  mediaBase = "https://zulu.hallotron.fyi/blogMedia/"
  defaultTheme = "auto"
  avatarAltText = "avatar"
  avatarSize = "size-m"
  # Remove leading slash: this will resolve to https://jurstu.github.io/blog/bg/output.png
  avatarURL = "https://blog.hallotron.fyi/bg/output.png"


[menu]

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    # remove leading slash
    url = "posts/"
    weight = 2

  [[menu.main]]
    name = "Pictures"
    pre = "<span data-feather='camera'></span>"
    url = "pictures/"
    weight = 3